# values used only if relevant command line arguments are not given to the dataset generator
models: ["cube_plane", "monkey"]
width: 500
height: 500
output: ["../outputs/images.npy", "../outputs/labels.npy"]

# other variables. These must not be deleted.
dontSave: Yes
verticalOffset: 0
scale: 10
cameraFocalLength: 1
azimuths: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340]
elevations: [30, 35, 40, 45, 50, 55, 60, 65, 70]
lightingPositions: ["noLights"]
